# Navigation Links

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 4

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[main]]
   name = "CV"
   url = "files/DhruvSingal_CV_20200228.pdf"
   weight = 7
