############################
## Theme
############################

# Choose a theme.
theme = "ocean"

# Enable users to switch between day and night mode?
day_night = true

# Choose a font size.
font_size = "L"

############################
## Basic Info
############################

# Website type
site_type = "Person"



# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Homepage for Dhruv Singal"

############################
## Site Features
############################

# Enable source code highlighting? true/false
highlight = true
highlight_languages = ["r"]  

# Enable LaTeX math rendering? true/false
math = true

# Enable diagram rendering? true/false
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false


############################
## Contact details
##
## These details power the Contact widget (if enabled).
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "dhruv.singal@gsb.columbia.edu"
phone = ""

# Address
address = {street = "Columbia Business School, c/o PhD Office, Uris Hall, 3022 Broadway", city = "New York", region = "NY", postcode = "10027", country = "United States", country_code = "US"}

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "skype", icon_pack = "fab", name = "singaldhruv", link = "skype:singaldhruv?call"},
  ]

############################
## Regional Settings
############################

# Date and time format
date_format = "Jan 2, 2006"
time_format = "3:04 PM"

# Address format 
address_format = "en-us"

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "r", show_logo = true}

# Show estimated reading time 
reading_time = false

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true 

# Enable in-built social sharing buttons? (true/false)
sharing = false

# Link authors to their profile page? (true/false)
link_authors = true

# Load JS plugins
plugins_js  = []

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Configuration of publication pages.
[publications]
  # Date format
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-127871705-1"
  google_tag_manager = ""

[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)
